### ISSUE TITLE
VirtualFlow GridPane

### ISSUE THREAD

**Issue by robinschmid** [FXMisc/Flowless#118]
Thanks for this great library. 
I was wondering if there are similar projects or if it would be easy to implement a GridPane in a virtualFlow. Given we have a List<Content> and we could specify that we want two columns and distribute space equally between the cells. 

Do you know of any project that achieves this or is it rather simple to implement?

Cheers
Robin

**Comment by Jugen** [comment]
Hi, if I understand your requirements correctly then it's simple to implement.
Try something like the following:
```java
var itemList = FXCollections.observableList( getItems() );

var flow = VirtualFlow.createVertical( itemList, item ->
{
	var grid = new GridPane();

	// configure gridpane and populate as required ....

	return Cell.wrapNode( grid );
});
```
Note that the above doesn't **reuse** _Cells_, so if building the GridPane contents is expensive and you would rather reuse Cells then you'll need to implement `Cell` instead. It's easy enough just look at the [Cell API doc](http://fxmisc.github.io/flowless/javadoc/0.7.0/org/fxmisc/flowless/Cell.html) and then override what you need.

**Comment by robinschmid** [comment]
Thanks for the quick response. 

The idea would be that we have a list of items but instead of having one column in the VirtualFlow I would like to have n columns. Either a fixed number or even able to adjust this. 

In you code one item defines a row - in my version each item still just defines one cell. So it is just a layout change.

One quick option would be to just split my initial item list into ObservableList<Item[]> so that we have one item describing a row and then I can use virtual flow... but just a question if there is a better way of achieving this.

**Comment by Jugen** [comment]
So do you want a horizontal flow instead ?
```java
VirtualFlow.createHorizontal( itemList, item -> ....
```

**Comment by robinschmid** [comment]
Scroll direction does not matter to me. 

One direction is scrolled and the other just auto fits it's content to the size. 

E.g., scroll vertically and put n cells per row.

**Comment by Jugen** [comment]
Ahh, I think you're looking for [TilePane](https://openjfx.io/javadoc/17/javafx.graphics/javafx/scene/layout/TilePane.html) then.

**Comment by robinschmid** [comment]
Yeah something like this. But TilePane does not use virtualization, as far as I understand. So it will always generate all cells even if they are not displayed off screen. 

Mine is like mapping a list into a gridpane in a scrollpane where each cell is similar.

**Comment by Jugen** [comment]
Okay so I assume you have a large list and you don't want each item to be rendered unnecessarily.
The challenge then in my mind is to somehow efficiently transform the List<Item> into List<Item[]> as you suggested and then render as per my first reply.

**Comment by robinschmid** [comment]
Thats what I thought. That should be fine.

**Comment by robinschmid** [comment]
@Jugen I actually totally missed that ControlsFX already had something that I was asking about. At least I think it is

https://controlsfx.github.io/features/gridview/

**Comment by Jugen** [comment]
Ahhh yes !  I forgot about that as well.  Good find :-)
