### ISSUE TITLE
Bidirectional binding of length properties does not update both values correctly

### ISSUE THREAD

**Issue by JordanMartinez** [FXMisc/Flowless#43]
As reported in TomasMikula/RichTextFX#535, binding two Vertical-Gravity Virtualized content's `estimatedScrollY` properties bidirectionally doesn't update them correctly. If the call is `prop1.bindBidirectionally(prop2)`, the two values will be correct whenever `prop1` scrolls but not when `prop2` scrolls.

**Comment by Fibii** [comment]
I had this same issue, but i found a workaround it, i used a `listener` on the `estimatedScrollYProperty` and then updated the other area using `setValue` as shown: 

`textArea.estimatedScrollYProperty().addListener((observable, oldValue, newValue) -> lineCounter.estimatedScrollYProperty().setValue(newValue));`
