### ISSUE TITLE
Issue with irregular size cell rendering

### ISSUE THREAD

**Issue by calvin-iyer** [FXMisc/Flowless#58]
Hi, I am facing an issue with implementing Flowless with irregular sized cells. Basically it doesn't populate a cell with data even if a part of it is visible in the viewport. This can be seen in the image below:
![scroll render issue](https://user-images.githubusercontent.com/13764389/33763488-aa14dca4-dc36-11e7-89e3-323216759ede.png)

This goes away if I scroll a few ticks down as seen below:
![scroll render issue 2](https://user-images.githubusercontent.com/13764389/33763487-a9eac7fc-dc36-11e7-96eb-cd77a9504fbf.png)

Another issue that I have is that it does not update the cell if the underlying data has been modified by the user. For example in the last image above the thumbnails should loose their borders once a user double clicks on them, but this does not happen with Flowless. It works fine if I use a ListView.

**Comment by JordanMartinez** [comment]
Hey @calvin-iyer. I apologize for my lack of response, but I have been going through finals. I don't expect to respond to you for a few more days, if not a week. I'm not as familiar with Flowless as RichTextFX, so it's hard for me to say what's causing your problem. Perhaps it's a bug. Perhaps you are configuring something incorrectly in a cell. 

For the time being, could you post a reproducible demo that shows the bug occurring?

**Comment by Jugen** [comment]
Closed - no demo provided.
