### ISSUE TITLE
Optional<Double> avgLen is present but is 0.0, resulting in dividing by zero, big numbers, and out of bounds error

### ISSUE THREAD

**Issue by komatr** [FXMisc/Flowless#63]
In the 0.6 release and also in master:

https://github.com/FXMisc/Flowless/blob/6466073fab157e885586ca4e8092b8ef0cf04d23/src/main/java/org/fxmisc/flowless/Navigator.java#L242-L245

I think we should check whether avgLen.isPresent() and Math.abs(avgLen.get()) < 1e-6, and if that's the case just set itemsBefore and itemsAfter to 5, same as what we do when avgLen is not present.

Otherwise, during layout, under some circumstances, avgLen is 0.0, itemsBefore is roughly 2^31, itemIndex - itemsBefore is a big negative number, after several function calls, the values are checked in reactfx and exception is thrown.

Maybe we should figure out why sizeTracker returns 0.0 as average length estimate, but that's beyond my knowledge of this project, and doing such a check before doing dividing seems reasonable enough to me.

**Comment by JordanMartinez** [comment]
Can you provide a reproducible demo?

**Comment by Jugen** [comment]
Closing - no demo provided.
