### ISSUE TITLE
Changing styles of rows

### ISSUE THREAD

**Issue by Arcnor** [FXMisc/Flowless#67]
This is really a question (I think), but I don't see any place to make those :).

For reusable cells, I change the classes associated with some of the elements when I reuse them. For example, my cell can be an `HBox` that contains a few `Label` elements. I try to change the classes on the labels, but when I scroll, Flowless applies the classes randomly (I'm changing colors with those classes).

Is there anything I can do to make this work, or is this a bug?

**Comment by JordanMartinez** [comment]
Could you provide a reproducible demo? And by `classes` do you mean style classes?

This is a good place to put questions.

**Comment by Arcnor** [comment]
Sure, I'll try to provide a demo. And yeah, I mean CSS classes.

**Comment by Jugen** [comment]
Closing - no demo provided.
