### ISSUE TITLE
org.fxmisc.flowless.CellListManager#getCellIfPresent

### ISSUE THREAD

**Issue by yqxu** [FXMisc/Flowless#89]
org.fxmisc.flowless.CellListManager#getCellIfPresent

changes the implementation as blow is better.

    public Optional<C> getCellIfPresent(int itemIndex) {
        if (itemIndex>=cells.size()||itemIndex<0){
            return Optional.empty();
        }
        return cells.getIfMemoized(itemIndex); // getIfMemoized() may throw
    }

**Comment by Jugen** [comment]
Thanks @yqxu, see PR #90
