### ISSUE TITLE
JavaFX 16

### ISSUE THREAD

**Issue by gringofe** [FXMisc/Flowless#91]
Hi,

is this library of any use for JavaFX versions `>8`? The benchmarks in the readme have been performed on very old JavaFX 8 builds, so I was wondering if it is still provides performance benefits on newer versions?

**Comment by Jugen** [comment]
I ran an updated version of the benchmark against JavaFX 16 and updated the table with the results.
VirtualFlow currently still seems to be better if the contents of the list changes a lot.

**Comment by gringofe** [comment]
Thank you!
